### ISSUE TITLE
pwhash.kdf_scryptsalsa208sha256 raises TypeError on parallelism factor

### ISSUE THREAD

**Issue by wilesproof** [pyca/pynacl#293] opened 2017-05-22 23:13 UTC
The pwhash.kdf_scryptsalsa208sah256 function raises a TypeError: the parallelism factor from nacl.bindings.nacl_bindings_pick_scrypt_params(SCRYPT_OPSLIMIT_SENSITIVE, SCRYPT_MEMLIMIT_SENSITIVE) returns a long, which causes the ensure() function to raise a TypeError (it expects an int).

pynacl version: 1.0.0-1.1.2 (maybe more)
Platform: Windows 8, Ubuntu 14.04, Ubuntu 16.04
Python version: 2.7.6

All versions were installed in fresh virtualenvs via pip install pynacl==-version-

**Comment by lmctv** [comment] 2017-05-28 09:33
Would you mind sending us some more informations about the runtime environment?
In particular, I'd like to see the output you get out of running:
``` python
import platform, sys
print(sys.version)
print(platform.architecture())
print(sys.version_info)
```
and  a terminal transcript of the reproducer, letting me wire-up a test case to enclose in the PR replacing 
```isinstance(n, int)``` with ```isinstance(p, integer_types)``` in ```crypto_pwhash_scryptsalsa208sha256_ll()```

**Comment by lmctv** [comment] 2017-06-02 11:55
@wilesproof ping

**Comment by lmctv** [comment] 2017-06-24 22:52
@wilesproof  Would you mind sending us some more informations about the runtime environment?
In particular, I'd like to see the output you get out of running:
``` python
import platform, sys
print(sys.version)
print(platform.architecture())
print(sys.version_info)
```
and  a terminal transcript of the reproducer, letting me wire-up a test case to enclose in the PR replacing 
```isinstance(n, int)``` with ```isinstance(p, integer_types)``` in ```crypto_pwhash_scryptsalsa208sha256_ll()```

**Comment by lmctv** [comment] 2017-06-26 06:55
@wilesproof the main question is if the runtime environments  you ran your tests in were 32 or 64 bit. Thank you

**Comment by lmctv** [comment] 2017-08-27 16:36
@wilesproof would you mind checking if current master works as you expect and this isuue could be closed?

**Comment by crwood** [comment] 2017-09-24 21:09
I also was bitten by this same bug (running version 1.1.2) but can confirm that the issue is resolved in current master.

To reproduce, I copied the [sample key derivation code](https://pynacl.readthedocs.io/en/1.1.2/password_hashing/#key-derivation) from the 1.1.2 docs directly to a file, ran it inside a virtualenv, and saw the following output:
```
Traceback (most recent call last):
  File "key_derivation.py", line 13, in <module>
    opslimit=ops, memlimit=mem)
  File "/home/user/pynacl/.tox/py27/local/lib/python2.7/site-packages/nacl/pwhash.py", line 77, in kdf_scryptsalsa208sha256
    password, salt, 2 ** n_log2, r, p, maxmem=maxmem, dklen=size)
  File "/home/user/pynacl/.tox/py27/local/lib/python2.7/site-packages/nacl/bindings/crypto_pwhash.py", line 151, in crypto_pwhash_scryptsalsa208sha256_ll
    raising=TypeError)
  File "/home/user/pynacl/.tox/py27/local/lib/python2.7/site-packages/nacl/exceptions.py", line 68, in ensure
    raise raising(*args)
TypeError
```

My environment was as follows:
```
2.7.13 (default, Jan 19 2017, 14:48:08)
[GCC 6.3.0 20170118]
('64bit', '')
sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0)
```

It might be worth noting that I was only able to reproduce the error on python2; the same code runs without issue on python3.5 and python3.6.

**Comment by lmctv** [comment] 2017-09-24 21:23
@crwood thank you very much for reproducing the bug, and confirming the fix is working. At last, I think this can be closed. If you don't mind, I'd like to know both the OS/distribution and the you ran your test on. Thank you once more.

**Closed by lmctv** 2017-09-24 21:23 UTC

**Comment by crwood** [comment] 2017-09-24 21:39
No problem!

I originally tested on Debian 9 ("stretch") but was also able to reproduce the exception on a Mac OS X 10.9 machine using the system python2 interpreter (2.7.5) inside a virtualenv. Like in the case of Debian, the issue was exclusive to python2; python 3.5 and 3.6 ran the same code just fine.
