### ISSUE TITLE
ImportError: Undefined symbol "crypto_pwhash_alg_argon2id13"

### ISSUE THREAD

**Issue by ex3me0** [pyca/pynacl#406] opened 2018-02-21 12:45 UTC
**OS:** FreeBSD 12
**Package:** PyNaCl==1.2.1 (installed without SODIUM_INSTALL=system, just pip install pynacl via virtualenv)
**System libsodium:** libsodium-1.0.12
```
Python 2.7.13 (default, Aug 29 2017, 16:07:39)
[GCC 4.2.1 Compatible FreeBSD Clang 5.0.0 (branches/release_50 311606)] on freebsd12
Type "help", "copyright", "credits" or "license" for more information.
>>> from nacl._sodium import ffi, lib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/ex/venv/lib/python2.7/site-packages/nacl/_sodium.so: Undefined symbol "crypto_pwhash_alg_argon2id13"
```
Seems python using bundled libsodium, but I see error like in case with a system library

**Comment by ex3me0** [comment] 2018-02-21 15:22
I did some investigation, which proves that _sodium.so requires system version of libsodium.
1. Rename `/usr/local/lib/libsodium.so.18.2.0`
2. Run: `python -c "from nacl._sodium import ffi, lib"`
`ImportError: Shared object "libsodium.so.18" not found, required by "_sodium.so"`

**Comment by ex3me0** [comment] 2018-02-22 11:26
```
(venv) $ ldd /venv/lib/python2.7/site-packages/nacl/_sodium.so
/venv/lib/python2.7/site-packages/nacl/_sodium.so:
        libthr.so.3 => /lib/libthr.so.3 (0x801622000)
        libsodium.so.18 => /usr/local/lib/libsodium.so.18 (0x80184a000)
        libpython2.7.so.1 => /usr/local/lib/libpython2.7.so.1 (0x801ac1000)
        libc.so.7 => /lib/libc.so.7 (0x800825000)
        libintl.so.8 => /usr/local/lib/libintl.so.8 (0x801ea5000)
        libutil.so.9 => /lib/libutil.so.9 (0x8020b0000)
        libm.so.5 => /lib/libm.so.5 (0x8022c4000)
```

**Comment by reaperhulk** [comment] 2018-02-22 12:12
Yeah, in the past this was a linker search path ordering issue (https://github.com/pyca/pynacl/commit/b525bd309623437f1e0a2c9e783afcdba91210c5).  Could you supply the build log as lmctv mentioned in the other issue?

**Comment by ex3me0** [comment] 2018-02-22 12:39
@reaperhulk sure: https://pastebin.com/G0ki8V9R

**Comment by reaperhulk** [comment] 2018-02-22 13:17
The order of linker libs looks okay, so I'm not sure what's going on here. Could you confirm that `build/temp.freebsd-12.0-CURRENT-LLBSD-2017.3.0-amd64-2.7/lib` contains a libsodium.so?

```
cc -shared -lpthread -L/usr/local/lib -fstack-protector build/temp.freebsd-12.0-CURRENT-LLBSD-2017.3.0-amd64-2.7/build/temp.freebsd-12.0-CURRENT-LLBSD-2017.3.0-amd64-2.7/_sodium.o -Lbuild/temp.freebsd-12.0-CURRENT-LLBSD-2017.3.0-amd64-2.7/lib -L/usr/local/lib -Lbuild/temp.freebsd-12.0-CURRENT-LLBSD-2017.3.0-amd64-2.7 -lsodium -lpython2.7 -lsodium -o build/lib.freebsd-12.0-CURRENT-LLBSD-2017.3.0-amd64-2.7/nacl/_sodium.so
```

**Comment by guidow** [comment] 2018-02-22 13:24
I'm experiencing a similar problem on OpenSuse 42.3 and Python 3:

    > python
    Python 3.4.6 (default, Mar 22 2017, 12:26:13) [GCC] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import nacl.signing
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/home/winkelmann/virtualenvs/pynacl-test/lib/python3.4/site-packages/nacl/signing.py", line 19, in <module>
        import nacl.bindings
    File "/home/winkelmann/virtualenvs/pynacl-test/lib/python3.4/site-packages/nacl/bindings/__init__.py", line 17, in <module>
        from nacl.bindings.crypto_box import (
    File "/home/winkelmann/virtualenvs/pynacl-test/lib/python3.4/site-packages/nacl/bindings/crypto_box.py", line 18, in <module>
        from nacl._sodium import ffi, lib
    ImportError: /home/winkelmann/virtualenvs/pynacl-test/lib/python3.4/site-packages/nacl/_sodium.cpython-34m.so: undefined symbol: crypto_pwhash_argon2id_opslimit_moderate

What I did was create a new virtualenv and run ```pip install pynacl``` in it.

Pynacl seems to be using the system libsodium here as well:

    > ldd /home/winkelmann/virtualenvs/pynacl-test/lib/python3.4/site-packages/nacl/_sodium.cpython-34m.so
            linux-vdso.so.1 (0x00007ffec5d13000)
            libsodium.so.18 => /usr/lib64/libsodium.so.18 (0x00007f9ca7db1000)
            libpython3.4m.so.1.0 => /usr/lib64/libpython3.4m.so.1.0 (0x00007f9ca794e000)
            libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f9ca7731000)
            libc.so.6 => /lib64/libc.so.6 (0x00007f9ca738c000)
            libdl.so.2 => /lib64/libdl.so.2 (0x00007f9ca7188000)
            libutil.so.1 => /lib64/libutil.so.1 (0x00007f9ca6f85000)
            libm.so.6 => /lib64/libm.so.6 (0x00007f9ca6c88000)
            /lib64/ld-linux-x86-64.so.2 (0x00007f9ca8231000)

**Comment by guidow** [comment] 2018-02-22 13:40
Some more observations: If I uninstall libsodium18 and libsodium-devel from the opensuse machine, pynacl cannot be installed. At the same time, on my Gentoo machine, where libsodium was never installed, pynacl builds and runs without a problem.

**Comment by reaperhulk** [comment] 2018-02-22 13:42
There's clearly some build toolchain weirdness going on there too, but bear in mind that if you're running on pip 8.1+ on either of those distributions it should grab a binary wheel and won't need to compile anything (thus bypassing the build toolchain problems).

(We can't distribute a wheel for FreeBSD so no such workaround available there).

**Comment by guidow** [comment] 2018-02-22 13:47
Pip on opensuse 42.3 is only on version 7.1.2.

**Comment by ex3me0** [comment] 2018-02-22 17:27
@reaperhulk only libsodium.a and libsodium.la, full dir listing below:
https://pastebin.com/QJ3QiTVe

**Comment by reaperhulk** [comment] 2018-02-23 03:00
Hmm, I wonder if the FreeBSD linker prioritizes shared objects over static linking so it's ignoring the libsodium.a in favor of the libsodium.so it's able to find later in the search path.

The object size makes sense. When it links against the static lib it will pull all the code associated with those symbols into _sodium.so. When it links against a shared lib it does not, so the file size is smaller.

**Comment by ex3me0** [comment] 2018-02-23 20:38
@reaperhulk thnx for or clarifying

**Just FYI**: I made several attempts to force bsd-linker/setuptools build_ext to use static library, but without success. 
At this time (just as a workaround) I use self-prepared custom build of PyNaCl, where libsodium sources was removed and replaced with pre-assembled _sodium.so, which included in setup.py as package_data (or data_files).
Ugly decision, but works for me, until no better options.
Simple example here: https://pastebin.com/1r7uKHY1
To build _sodium.so I took advantage of this advice: https://github.com/pyca/pynacl/issues/281#issuecomment-289971152

**Comment by lmctv** [comment] 2018-03-18 09:58
@ex3me0 I don't really understand what's happening there, since (as you noted) the link order problem was seemingly solved with release 1.1.2, as confirmed from @yurivict . Are trying to install in a virtualenv, or to run the system-level port's Makefile?

**Comment by mirceaulinic** [comment] 2018-03-18 20:46
I am also experiencing a similar issue on OpenBSD (though the error message is not exactly the same - but it still complains about two undefined objects: `crypto_pwhash_str_needs_rehash` and `crypto_pwhash_str_alg` from the same `_sodium.so`):

```python
[GCC 4.2.1 Compatible OpenBSD Clang 4.0.0 (tags/RELEASE_400/final)] on openbsd6
Type "help", "copyright", "credits" or "license" for more information.
>>> from nacl._sodium import ffi, lib
python:/usr/local/venvs/pynacl/lib/python2.7/site-packages/nacl/_sodium.so: undefined symbol 'crypto_pwhash_str_needs_rehash'
python:/usr/local/venvs/pynacl/lib/python2.7/site-packages/nacl/_sodium.so: undefined symbol 'crypto_pwhash_str_alg'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: Cannot load specified object
>>> import nacl
>>> nacl.__version__
'1.2.1'
```

Downgrading to a previous version, I don't see any issues:

```python
>>> import nacl
>>> nacl.__version__
'1.1.0'
>>> from nacl._sodium import ffi, lib
>>> 
```

**Comment by lmctv** [comment] 2018-03-24 18:35
@guidow could you please try to fetch and test if #417 solves your problems, by executing
```
$ git fetch origin pull/417/head:local-linkpath-test
$ git checkout local-linkpath-test
```
and then trying to build pynacl in a clean virtualenv, with updated pip and setuptools
```
$ ${venv_path}/bin/pip install --upgrade setuptools
$ ${venv_path}/bin/pip install --upgrade pip
```

**Comment by lmctv** [comment] 2018-03-24 18:44
@mirceaulinic: which openbsd version and processor are you using?

**Comment by lmctv** [comment] 2018-04-01 19:24
After spending some more time on testing the behaviour of both a dist-packaged and a manually built python interpreter on *BSDs, I see  the command line flags `-I/usr/local/include` and `-L /usr/local/lib` come from upstream python sources; therefore, the only thing we can do for *BSDs is document the following alternatives:

   - choose a pynacl version compatible to the pkg installed libsodium version if building with `SODIUM_INSTALL="system"`;
   - remove/mask the libsodium package before building;
   - build in a pristine system;
   - create a clean jail just to build pynacl wheels;

Any documentation suggestion or PR coming from an experienced *BSD user would surely be better than what I could whip, being mainly a linux sysadmin myself.

**Comment by lmctv** [comment] 2018-04-01 19:39
Closing in favour of #420 and #421 .

**Closed by lmctv** 2018-04-01 19:39 UTC
