### ISSUE TITLE
AttributeError: cffi library '_sodium' has no function, constant or global variable named 'crypto_box_seedbytes'

### ISSUE THREAD

**Issue by Harmon758** [pyca/pynacl#474] opened 2018-09-19 01:01 UTC
This error is occurring when importing `nacl.bindings.crypto_box`.
See https://github.com/Rapptz/discord.py/issues/1593.

Other relevant issues:
https://github.com/ktbyers/netmiko/issues/747
https://github.com/digitalocean/netbox/issues/2130
https://github.com/bigchaindb/bigchaindb/issues/2511 (with relevant Read the Docs build: https://readthedocs.org/projects/bigchaindb-server/builds/7732907/)

Based on reports from the discord.py community and these other issues, this seems to happen on Ubuntu, with PyNaCl 1.2.0 and 1.2.1 (but not 1.1.2). However, in some cases, that setup doesn't reproduce the error.
This error doesn't seem to occur with the `PYNACL_SODIUM_STATIC` flag enabled.
Also, it doesn't appear to be specific to a Python version.

**Comment by reaperhulk** [comment] 2018-09-19 01:05
These sorts of problems are typically a product of a broken python package environment. If we can reproduce it in a fresh virtualenv then we have a bug we can resolve, but otherwise we're stuck.

Additionally, if you run a new pip it will give you a prebuilt wheel and no compilation will be required, which will bypass any linking issues like this.

**Comment by Harmon758** [comment] 2018-09-19 01:29
Sorry, something I forgot to mention was that this seems to happen regardless of whether using a wheel or compiling manually. Someone with the issue installed with a wheel from PyPI and still encountered the issue.

I believe Read the Docs uses a fresh virtualenv, so it seems to be reproduceable, but I'm not sure what the required conditions are.

Something else unusual I noticed, that might or might not be relevant, is that directly before the first [BigchainDB Server Read the Docs build that failed](https://readthedocs.org/projects/bigchaindb-server/builds/7732867/), there was [one that succeeded](https://readthedocs.org/projects/bigchaindb-server/builds/7732523/). However, the only change in that commit was to a README. There was also [another build that succeeded](https://readthedocs.org/projects/bigchaindb-server/builds/7733384/) after the second one that failed and before they reverted to an older version of PyNaCl.

**Comment by reaperhulk** [comment] 2018-09-19 01:46
Hmm, maybe this could be a dynamic linker precedence problem? Where the system has an older libsodium and pynacl has a newer one, but the wrong one is loaded at runtime. @lmctv didn't we do something around the dynamic linker ordering awhile back?

**Comment by lmctv** [comment] 2018-10-29 19:29
Since @Harmon758  told the exception doesn't happen if PYNACL_SODIUM_STATIC is set while building, I think the linking flags are correct now. If the system provided libsodium is missing those symbols, they get resolved in the locally built shared library and then missed after module installation.

**Comment by Gorialis** [comment] 2018-12-21 19:22
While I forgot to mention it when this issue first turned up, I've had a decent amount of involvement with this issue as it originally turned up when a few of our users were experiencing it on the discord.py Discord support server (discord.py uses PyNaCl for secure voice connections). As this has recently been brought back to my attention, I figured I would document as much information as I knew here.

Some more minor observations first:
- All users who have reported this issue on the server had been using either Ubuntu 18.04 or a derivative (specifically, one user encountered it on Kubuntu 18.04)
- All specific instances of this issue occuring were when PyNaCl was installed using the `--user` flag (placing it into `/home/user/.local/...`)

I asked one of the users to give me their `dir(nacl._sodium.lib)` for their install. Subtracting theirs from mine on the same version (but a working install), revealed that all of the following were NOT present in their install, with the specific one in this issue underlined (I no longer have a puretext version of this, unfortunately):

![image](https://user-images.githubusercontent.com/8049998/50358523-f847c180-059c-11e9-925f-585328f27d5d.png)

From this, it seemed that the wrong version of sodium was being targeted somehow. After poking around looking at how the module was created, I found [the `PYNACL_SODIUM_STATIC` flag](https://github.com/pyca/pynacl/blob/master/src/bindings/build.py#L44) and decided to see if making the user enable this flag fixed the problem. To my (somewhat) surprise it did, and getting the remainder of the affected users to try it solved the problem in every case. From there it was tagged as the informal fix for the issue on the server, hence its reproduction here.

Unfortunately, I wasn't able to probe too much further than this, as I was unable to reproduce the issue on any of my own environments and the affected users, now having a fix, were fairly disinterested in allowing me to do any further investigating on their machines.

I had thought for a while that this issue had been either intentionally or inadvertently resolved (such as e.g. via an Ubuntu update) but it seems it may have just been a lack of reports as it has recently [appeared again](https://github.com/Rapptz/discord.py/issues/1793). I'll try to do more testing to see if I can reproduce this issue myself, and I'll report here if I find anything I think is of use.

**Comment by lmctv** [comment] 2018-12-23 12:18
I don't know how relevant it could be, but while the link-order corrections got merged in release 1.1.2,  the extras_require in discord.py's setup.py mention PyNaCl==1.0.1.

The  PYNACL_SODIUM_STATIC flag should have no effect under non-windows systems, since it's meant to alter symbol visibility when compiling and linking code calling libsodium under visual studio.

Also, I don't understand the reason why pip is compiling the module from source instead of downloading the pre-built wheels, but this is all moot, since I've just built  both versions in a clean ubuntu bionic environment, and the resultant binaries were self-contained, not referencing a external libsodium shared object.

Furthermore, since the bionic provided version of libsodium is aligned with the bundled version, even building with the former should lead to a working nacl module.

Feel free to reopen if you could find a reproducer.

**Closed by lmctv** 2018-12-23 12:18 UTC
Labels: missing-reproducer

**Comment by ionadev** [comment] 2019-04-07 08:38
I Am Able To Reproduce It, Here is what i get 
```
File "bot.py", line 1, in <module>
    import discord
  File "/home/piyush/.local/lib/python3.6/site-packages/discord/__init__.py", line 23, in <module>
    from .client import Client
  File "/home/piyush/.local/lib/python3.6/site-packages/discord/client.py", line 37, in <module>
    from .user import User, Profile
  File "/home/piyush/.local/lib/python3.6/site-packages/discord/user.py", line 29, in <module>
    import discord.abc
  File "/home/piyush/.local/lib/python3.6/site-packages/discord/abc.py", line 39, in <module>
    from .voice_client import VoiceClient
  File "/home/piyush/.local/lib/python3.6/site-packages/discord/voice_client.py", line 55, in <module>
    import nacl.secret
  File "/home/piyush/.local/lib/python3.6/site-packages/nacl/secret.py", line 17, in <module>
    import nacl.bindings
  File "/home/piyush/.local/lib/python3.6/site-packages/nacl/bindings/__init__.py", line 17, in <module>
    from nacl.bindings.crypto_box import (
  File "/home/piyush/.local/lib/python3.6/site-packages/nacl/bindings/crypto_box.py", line 27, in <module>
    crypto_box_SEEDBYTES = lib.crypto_box_seedbytes()
AttributeError: cffi library '_sodium' has no function, constant or global variable named 'crypto_box_seedbytes'
```

**Comment by Gorialis** [comment] 2019-04-15 14:29
Bumping to say that this issue (or a variant of it) seems to still be present on users running PyNaCl v1.3.0, and that experiencers on this version are no longer able to fix it with the `PYNACL_SODIUM_STATIC=true` trick (although, I'm not sure why this trick worked in the first place).

The issue seems to now appear from this stack:
https://github.com/pyca/pynacl/blob/4881c878c9a33f4684337f650355bdf7f031d77d/src/nacl/bindings/__init__.py#L17
https://github.com/pyca/pynacl/blob/4881c878c9a33f4684337f650355bdf7f031d77d/src/nacl/bindings/crypto_aead.py#L28
producing `AttributeError: cffi library 'sodium' has no function, constant or global variable named 'crypto_aead_chacha20poly1305_ietf_keybytes`.

Like before, the issue seems to only appear in user installs, and appears primarily on variants of Ubuntu Bionic (18.04), and has been reported both on headless VPS hosts and desktop installs.

**Comment by reaperhulk** [comment] 2019-04-16 06:11
@Gorialis it'd be useful if someone could provide a docker container that replicates this issue. I can't replicate it with a naïve 18.04 container, but it's possible I'm doing something unusual.

**Comment by jcopps** [comment] 2019-04-19 06:13
Downgrading PyNacl to 1.2.1 helped.

**Comment by Pooky-s** [comment] 2019-07-03 12:27
I downgraded PyNacl to 1.2.1, didn't helped :c

**Comment by reaperhulk** [comment] 2019-07-03 14:11
This issue is essentially always due to having more than one pynacl installed in your python path (typically by your OS package manager in addition to pip). If you are able to install and run pynacl successfully in a virtualenv then you have an issue in your environment.
