### ISSUE TITLE
pynacl defaults to blocking random - causes paramiko to hang on import

### ISSUE THREAD

**Issue by Kkevsterrr** [pyca/pynacl#503] opened 2019-01-13 01:55 UTC
Hey pynacl team - 

I recently ran into an issue with paramiko (see here https://github.com/paramiko/paramiko/issues/1368 ), which looks like is actually under the hood an issue with pynacl blocking on randomness. Would it be possible to change the default behavior from blocking on randomness to not blocking on randomness? I'm open to any other insights or ideas you may have! Thanks!

**Comment by ploxiln** [comment] 2019-01-13 02:09
it looks like this is related to #327

**Comment by alex** [comment] 2019-01-13 03:02
Going to go ahead and close as a dupe of that one, if you think this has a different root cause we can reopen.

**Closed by alex** 2019-01-13 03:02 UTC
