### ISSUE TITLE
some of the tests take longer than expected on slow machines -> FAIL

### ISSUE THREAD

**Issue by ignatenkobrain** [pyca/pynacl#370] opened 2017-11-02 08:20 UTC
```python
=================================== FAILURES ===================================
_________________________ test_argon2i_str_and_verify __________________________
    @given(text(alphabet=PASSWD_CHARS, min_size=5, max_size=20),
>          integers(min_value=4,
                    max_value=6),
           integers(min_value=1024 * 1024,
                    max_value=16 * 1024 * 1024)
           )
    @settings(deadline=1500, max_examples=20)
    def test_argon2i_str_and_verify(password, ops, mem):
tests/test_pwhash.py:409: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python2.7/site-packages/hypothesis/executors.py:58: in default_new_style_executor
    return function(data)
/usr/lib/python2.7/site-packages/hypothesis/core.py:136: in run
    return test(*args, **kwargs)
tests/test_pwhash.py:409: in test_argon2i_str_and_verify
    integers(min_value=4,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
args = ('   𧰒 ', 5, 15794431), kwargs = {}, start = 1509610662.526979
result = None, runtime = 1874.4771480560303
    @proxies(test)
    def timed_test(*args, **kwargs):
        self.__test_runtime = None
        start = time.time()
        result = test(*args, **kwargs)
        runtime = (time.time() - start) * 1000
        self.__test_runtime = runtime
        if self.settings.deadline is not_set:
            if (
                not self.__warned_deadline and
                runtime >= 200
            ):
                self.__warned_deadline = True
                note_deprecation((
                    'Test took %.2fms to run. In future the default '
                    'deadline setting will be 200ms, which will '
                    'make this an error. You can set deadline to '
                    'an explicit value of e.g. %d to turn tests '
                    'slower than this into an error, or you can set '
                    'it to None to disable this check entirely.') % (
                        runtime, ceil(runtime / 100) * 100,
                ))
        elif runtime >= self.current_deadline:
>           raise DeadlineExceeded(runtime, self.settings.deadline)
E           DeadlineExceeded: Test took 1874.48ms, which exceeds the deadline of 1500.00ms
/usr/lib/python2.7/site-packages/hypothesis/core.py:624: DeadlineExceeded
---------------------------------- Hypothesis ----------------------------------
Falsifying example: test_argon2i_str_and_verify(password=u'   \U00027c12 ', ops=5, mem=15794431)
You can add @seed(76691214557540253359885305968315728619) to this test or run pytest with --hypothesis-seed=76691214557540253359885305968315728619 to reproduce this failure.
_______________________ test_argon2i_str_and_verify_fail _______________________
    @given(text(alphabet=PASSWD_CHARS, min_size=5, max_size=20),
>          integers(min_value=4,
                    max_value=6),
           integers(min_value=1024 * 1024,
                    max_value=16 * 1024 * 1024)
           )
    @settings(deadline=1500, max_examples=20)
    def test_argon2i_str_and_verify_fail(password, ops, mem):
tests/test_pwhash.py:437: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python2.7/site-packages/hypothesis/executors.py:58: in default_new_style_executor
    return function(data)
/usr/lib/python2.7/site-packages/hypothesis/core.py:136: in run
    return test(*args, **kwargs)
tests/test_pwhash.py:437: in test_argon2i_str_and_verify_fail
    integers(min_value=4,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
args = ('   ƒ𣁬', 6, 15695904), kwargs = {}, start = 1509610735.343385
result = None, runtime = 2215.2600288391113
    @proxies(test)
    def timed_test(*args, **kwargs):
        self.__test_runtime = None
        start = time.time()
        result = test(*args, **kwargs)
        runtime = (time.time() - start) * 1000
        self.__test_runtime = runtime
        if self.settings.deadline is not_set:
            if (
                not self.__warned_deadline and
                runtime >= 200
            ):
                self.__warned_deadline = True
                note_deprecation((
                    'Test took %.2fms to run. In future the default '
                    'deadline setting will be 200ms, which will '
                    'make this an error. You can set deadline to '
                    'an explicit value of e.g. %d to turn tests '
                    'slower than this into an error, or you can set '
                    'it to None to disable this check entirely.') % (
                        runtime, ceil(runtime / 100) * 100,
                ))
        elif runtime >= self.current_deadline:
>           raise DeadlineExceeded(runtime, self.settings.deadline)
E           DeadlineExceeded: Test took 2215.26ms, which exceeds the deadline of 1500.00ms
/usr/lib/python2.7/site-packages/hypothesis/core.py:624: DeadlineExceeded
---------------------------------- Hypothesis ----------------------------------
Falsifying example: test_argon2i_str_and_verify_fail(password=u'   \u0192\U0002306c', ops=6, mem=15695904)
You can add @seed(302934307671667531413257853548643485645) to this test or run pytest with --hypothesis-seed=302934307671667531413257853548643485645 to reproduce this failure.
__________________________ test_pwhash_str_and_verify __________________________
    @given(text(alphabet=PASSWD_CHARS, min_size=5, max_size=20))
>   @settings(deadline=1500, max_examples=5)
    def test_pwhash_str_and_verify(password):
tests/test_pwhash.py:451: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python2.7/site-packages/hypothesis/executors.py:58: in default_new_style_executor
    return function(data)
/usr/lib/python2.7/site-packages/hypothesis/core.py:136: in run
    return test(*args, **kwargs)
tests/test_pwhash.py:451: in test_pwhash_str_and_verify
    @settings(deadline=1500, max_examples=5)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
args = ('     ',), kwargs = {}, start = 1509610793.560199, result = None
runtime = 6905.997037887573
    @proxies(test)
    def timed_test(*args, **kwargs):
        self.__test_runtime = None
        start = time.time()
        result = test(*args, **kwargs)
        runtime = (time.time() - start) * 1000
        self.__test_runtime = runtime
        if self.settings.deadline is not_set:
            if (
                not self.__warned_deadline and
                runtime >= 200
            ):
                self.__warned_deadline = True
                note_deprecation((
                    'Test took %.2fms to run. In future the default '
                    'deadline setting will be 200ms, which will '
                    'make this an error. You can set deadline to '
                    'an explicit value of e.g. %d to turn tests '
                    'slower than this into an error, or you can set '
                    'it to None to disable this check entirely.') % (
                        runtime, ceil(runtime / 100) * 100,
                ))
        elif runtime >= self.current_deadline:
>           raise DeadlineExceeded(runtime, self.settings.deadline)
E           DeadlineExceeded: Test took 6906.00ms, which exceeds the deadline of 1500.00ms
/usr/lib/python2.7/site-packages/hypothesis/core.py:624: DeadlineExceeded
---------------------------------- Hypothesis ----------------------------------
Falsifying example: test_pwhash_str_and_verify(password=u'     ')
You can add @seed(302934307671667531413257853548643485645) to this test or run pytest with --hypothesis-seed=302934307671667531413257853548643485645 to reproduce this failure.
============== 3 failed, 4517 passed, 4 skipped in 504.19 seconds ==============
```

```
CPU info:
Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Model:               1
Model name:          ARMv7 Processor rev 1 (v7l)
BogoMIPS:            100.00
Flags:               half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm


Memory:
              total        used        free      shared  buff/cache   available
Mem:       24929660      136776    24101132         372      691752    24482960
Swap:      18869244        4404    18864840


Storage:
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda2       135G  3.5G  124G   3% /
```

**Comment by lmctv** [comment] 2017-11-02 10:12
First, a question: are the memory sizes in your report measured in bytes or kibibytes? In other words, are you trying to run the tests on a 24MiB system, or did you manage to get hold of a 24GiB system with such a slow CPU?

Next, I'm going to try and add pytest support for handling low-memory/low-speed systems, but I don't expect such changes to get released in the 1.2.x stream; still, I'd be grateful for any help you'll be able to give on testing the master branch on such configured systems.

In the meanwhile, since you are manually building, I think the correct option for your use-case would be to manually extend the deadline to 5000ms in thise tests.

Thank you very much.

**Comment by ignatenkobrain** [comment] 2017-11-02 10:17
> did you manage to get hold of a 24GiB system with such a slow CPU

This, it is builder in Fedora Infrastructure. ARM is such slow by design, but there is no problems with getting such amount of memory.

> I'd be grateful for any help you'll be able to give on testing the master branch on such configured systems.

Sure, just let me know what to test ;)

Also it is not **that** slow, but way slower than s390x/ppc64/ppc64le/x86_64/aarch64. The plan is to emulate armv7 on aarch64, but qemu still has some bugs so it's not ready yet.

**Comment by kitterma** [comment] 2018-03-14 20:34
I ran into very similar problems when I updated to 1.2.1 in Debian.  The package build failed on all three mips variants we have and two of two 32 bit arm variants.  It also failed on a number of older non-release architectures [1].  As suggested here, I bumped the deadline, although to a much higher number because some of our slow architectures are REALLY slow.  You can look at some of the linked build logs for details if you are interested.

Once I did that, I still ran into  a problem with timeout on a few architectures [2] is one example.

Fundamentally, slow architectures are slow and so time related test constraints aren't going to work across the board.  If you set the values high enough that the slow architectures complete the tests, then you aren't testing anything on the faster architectures where development typically occurs and finding performance regressions is really important.

Solving the second problem is pretty trivial.  The timeout parameter is deprecated by hypothesis [3] and will be removed in the future.  I think the clear answer is to set timeout to unlimited (which is what the hypothesis documentation recommends and will happen anyway when it is removed).  I'll prepare a merge request for this and submit it shortly.

To make deadline useful across a range of processing architectures, it needs to be adjustable.  At least in Debian, controlling this on a per-architecture basis via an environment variable set in our Make file is a pretty standard way to deal with problems like that.  

The current hard coded value for deadline is 1500 milliseconds.  If a solution that set the value for deadline using something like os.getenv(PYNACL_HYPOTHESIS_DEADLINE, 1500) would be acceptable upstream, I can prepare a merge requests for that too.

[1] https://buildd.debian.org/status/logs.php?pkg=python-nacl&ver=1.2.1-1&suite=sid
[2] https://buildd.debian.org/status/fetch.php?pkg=python-nacl&arch=mipsel&ver=1.2.1-2&stamp=1520919082&raw=0
[3] http://hypothesis.readthedocs.io/en/latest/settings.html?highlight=timeout

**Comment by kitterma** [comment] 2018-03-14 20:49
First pull request is submitted. https://github.com/pyca/pynacl/pull/411

**Comment by kitterma** [comment] 2018-04-02 20:58
@lmctv - not sure if you're following PR #416 or not, but just in case, your feedback is requested on just using None for deadline.

**Comment by kitterma** [comment] 2018-04-02 21:00
That or I can't read and what I meant to say was:

@ignatenkobrain - not sure if you're following PR  #416  or not, but just in case, your feedback is requested on just using None for deadline.

**Comment by lmctv** [comment] 2018-04-05 05:50
Closing, since hypothesis induced exceptions have been disabled via #411 and #416

**Closed by lmctv** 2018-04-05 05:50 UTC
